<meta charset="utf-8" />
CREATE DATABASE `EDT`;

CREATE TABLE `EDT`.`Utilisateur` (`ID` INT(10) NOT NULL AUTO_INCREMENT,`Email` Varchar(50) NOT NULL, `PASSWD` Varchar(50) NOT NULL, `Nom` Varchar(50) NOT NULL,`Prenom` Varchar(50) NOT NULL, `Droit` int(5) NOT NULL, PRIMARY KEY (`ID`)) ENGINE = MyISAM; 
CREATE TABLE `EDT`.`Promotion` (`ID` INT(10) NOT NULL AUTO_INCREMENT, `Nom` Varchar(50) NOT NULL, PRIMARY KEY (`ID`)) ENGINE = MyISAM; 
CREATE TABLE `EDT`.`Groupe` (`ID` INT(10) NOT NULL AUTO_INCREMENT, `Nom` Varchar(50) NOT NULL,`IDPromotion` INT(10) NOT NULL, PRIMARY KEY (`ID`),FOREIGN KEY (IDPromotion) REFERENCES Promotion(ID)) ENGINE = MyISAM; 

CREATE TABLE `EDT`.`Etudiant` (`ID_Utilisateur` INT(10) NOT NULL,`Numero` INT(10) NOT NULL,`ID_Groupe` INT(10) NOT NULL, PRIMARY KEY (`ID_Utilisateur`),FOREIGN KEY (ID_Utilisateur) REFERENCES Utilisateur(ID),FOREIGN KEY (ID_Groupe) REFERENCES Groupe(ID)) ENGINE = MyISAM; 
CREATE TABLE `EDT`.`Cours` (`ID` INT(10) NOT NULL AUTO_INCREMENT, `Nom` Varchar(50) NOT NULL, PRIMARY KEY (`ID`)) ENGINE = MyISAM; 

CREATE TABLE `EDT`.`Type_Cours` (`ID` INT(10) NOT NULL AUTO_INCREMENT, `Nom` Varchar(50) NOT NULL, PRIMARY KEY (`ID`)) ENGINE = MyISAM; 

CREATE TABLE `EDT`.`Enseignant` (`ID_Utilisateur` INT(10) NOT NULL, `ID_Cours` INT(10) NOT NULL, PRIMARY KEY (`ID_Utilisateur`,`ID_Cours`),FOREIGN KEY (ID_Utilisateur) REFERENCES Utilisateur(ID),FOREIGN KEY (ID_Cours) REFERENCES Cours(ID)) ENGINE = MyISAM; 


CREATE TABLE `EDT`.`Site` (`ID` INT(10) NOT NULL AUTO_INCREMENT, `Nom` Varchar(50) NOT NULL, PRIMARY KEY (`ID`)) ENGINE = MyISAM; 

CREATE TABLE `EDT`.`Salle` (`ID` INT(10) NOT NULL AUTO_INCREMENT, `Nom` Varchar(50) NOT NULL,`Capacite` INT(10) NOT NULL, `ID_Site` INT(10) NOT NULL,PRIMARY KEY (`ID`),FOREIGN KEY (ID_Site) REFERENCES Site(ID)) ENGINE = MyISAM; 

CREATE TABLE `EDT`.`Seance` (`ID` INT(10) NOT NULL AUTO_INCREMENT,`SEMAINE` INT(10) NOT NULL,`Date` Date NOT NULL , `Heure_Debut` Time NOT NULL,`Heure_Fin` Time NOT NULL,`Nom` Varchar(50) NOT NULL, `Etat` int(10) NOT NULL,`ID_Cours` INT(10) NOT NULL,`ID_Type` INT(10) NOT NULL, PRIMARY KEY (`ID`),FOREIGN KEY (ID_Cours) REFERENCES Cours(ID),FOREIGN KEY (ID_Type) REFERENCES Type_Cours(ID)) ENGINE = MyISAM; 

CREATE TABLE `EDT`.`Seance_Groupe` (`ID_Seance` INT(10) NOT NULL , `ID_Groupe` INT(10) NOT NULL, PRIMARY KEY (`ID_Seance`,`ID_Groupe`),FOREIGN KEY (ID_Seance) REFERENCES Seance(ID),FOREIGN KEY (ID_Groupe) REFERENCES Groupe(ID)) ENGINE = MyISAM; 

CREATE TABLE `EDT`.`Seance_Enseignants` (`ID_Seance` INT(10) NOT NULL , `ID_Enseignant` INT(10) NOT NULL, PRIMARY KEY (`ID_Seance`,`ID_Enseignant`),FOREIGN KEY (ID_Seance) REFERENCES Seance(ID),FOREIGN KEY (ID_Enseignant) REFERENCES Enseignant(ID)) ENGINE = MyISAM; 

CREATE TABLE `EDT`.`Seance_Salles` (`ID_Seance` INT(10) NOT NULL , `ID_Salle` INT(10) NOT NULL, PRIMARY KEY (`ID_Seance`,`ID_Salle`),FOREIGN KEY (ID_Seance) REFERENCES Seance(ID),FOREIGN KEY (ID_Salle) REFERENCES Salle(ID)) ENGINE = MyISAM; 

